config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#homepage'

  get 'users/show/:id' => 'users#show', as: 'profile_page'

  get 'braintree/new'
  post 'braintree/checkout'

  get 'coinbase/new'
  post 'coinbase/checkout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :offers
  resources :requests
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :user
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
	before_action :set_request, only: [:show, :edit, :update, :destroy]
	before_action :check_owner, only: [:edit, :update, :destroy]


	def index
		@requests = current_user.requests.order("created_at DESC")#.page(params[:page]) <--- Uncomment this out after we do the paginate gem
	end

	def new
		@request = Request.new
	end

	def create
		@request = current_user.requests.new(request_params)
	    if @request.save
	     	 redirect_to requests_path
	    else
	      render template: "requests/new"
	    end
	end

	def edit
		@request = Request.find(params[:id])
	end

	def update
		@request = Request.find(params[:id])
    @request.update(request_params)
    redirect_to requests_path
	end

	def show
		@request = Request.find(params[:id])
	end

	def destroy
		@request = Request.find(params[:id])
    @request.destroy
    redirect_to requests_path
	end

	private
	def set_request
		@request = Request.find(params[:id])
	end

	def check_owner
    unless @request.user_id == current_user.id
      redirect_to root_path, notice: "You are not allowed to access that page."
    end
  end

	def request_params
    params.require(:request).permit(:title, :request_description, :request_category, :token, :description, :photo)
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<div class="text-field">
	<%= form.label :Title %>
	<%= form.text_field :title %>
</div>

<div class="text-field">
	<%= form.label :Category %>
	<%= form.text_field :request_category %>
</div>

<div class="text-field">
	<%= form.label :Description %>
	<%= form.text_field :request_description %>
</div>

<div class="text-field">
	<%= form.label :Ora_Coins_Payments %>
	<%= form.text_field :token %>
</div>

<div class="file-field">
	<%= form.label :Photo %>
	<%= form.file_field :photo %>
</div>

app/views/requests/edit.html.erb
<%= link_to "Home", root_path %>

<h1>Update your Ora Request here</h1>
<p>Current Request Information</p>

<%= form_for @request do |form| %>
	<%= render partial: '/requests/form', object: form %>

  <%= form.submit %>
<% end %>

app/views/requests/index.html.erb
<%= link_to "Home", root_path %><br>
<%= link_to "Create a new request", new_request_path %>
<h1>My Requests</h1>

<% @requests.each do |request| %>
<%= link_to "Edit Request", edit_request_path(request) %>
<%= link_to "Delete", request_path(request), method: :delete, data: { confirm: 'Are you sure?' } %>
<p><%= link_to "Title : #{request.title}", request_path(request) %></p>
<p>Ora Coins Reward : <%= request.token %> Ora Coins</p>
<%= link_to "Coinbase", "/auth/coinbase" %>
<p>Category : <%= request.request_category %></p>
<p>Description : <%= request.request_description %></p>
<p>Created at <%= time_ago_in_words(request.created_at) %> ago</p>
<p>--------------------------------------------------------------</p>

<% end %>

app/views/requests/new.html.erb
<h1>Create New Ora Request here</h1>
<%= link_to "Home", root_path %>
<p></p>
<%= form_for @request do |form| %>
	<%= render partial: '/requests/form', object: form %>

  <%= form.submit %>
<% end %>

app/views/requests/show.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Back", requests_path %>
<h1>This is the show page for <%= @request.user.email %></h1>


<p>Title : <%= @request.title %></p>
<p>Ora Coins Reward : <%= @request.token %> Ora Coins</p>
<p>Category : <%= @request.request_category %></p>
<p>Description : <%= @request.request_description %></p>
<p>Created at <%= time_ago_in_words(@request.created_at) %> ago</p>