config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#homepage'

  get 'users/show/:id' => 'users#show', as: 'profile_page'

  get 'braintree/new'
  post 'braintree/checkout'

  get 'coinbase/new'
  post 'coinbase/checkout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :offers
  resources :requests
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  # mount_uploader :images, ImagesUploader
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	before_action :set_offer, only: [:show, :edit, :update, :destroy]
	before_action :check_owner, only: [:edit, :update, :destroy]


	def index
		@offers = current_user.offers.order("created_at DESC")#.page(params[:page]) <--- Uncomment this out after we do the paginate gem
	end

	def new
		@offer = Offer.new
	end

	def create
		@offer = current_user.offers.new(offer_params)
	    if @offer.save
	     	 redirect_to offers_path
	    else
	      render template: "offers/new"
	    end
	end

	def edit
		@offer = Offer.find(params[:id])
	end

	def update
		@offer = Offer.find(params[:id])
    @offer.update(offer_params)
    redirect_to offers_path
	end

	def show
		@offer = Offer.find(params[:id])
	end

	def destroy
		@offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to requests_path
	end

	private
	def set_offer
		@offer = Offer.find(params[:id])
	end

	def check_owner
    unless @offer.user_id == current_user.id
      redirect_to root_path, notice: "You are not allowed to access that page."
    end
  end

	def offer_params
    params.require(:offer).permit(:title, :offer_description, :offer_category, :token, :description, :photo)
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<div class="text-field">
	<%= form.label :Title %>
	<%= form.text_field :title %>
</div>

<div class="text-field">
	<%= form.label :Category %>
	<%= form.text_field :offer_category %>
</div>

<div class="text-field">
	<%= form.label :Description %>
	<%= form.text_field :offer_description %>
</div>

<div class="text-field">
	<%= form.label :Ora_Coins_Charges %>
	<%= form.text_field :token %>
</div>

<div class="file-field">
	<%= form.label :Photo %>
	<%= form.file_field :photo %>
</div>

app/views/offers/edit.html.erb
<%= link_to "Home", root_path %>

<h1>Update your Ora Offer here</h1>
<p>Current Offer Information</p>

<%= form_for @offer do |form| %>
	<%= render partial: '/offers/form', object: form %>

  <%= form.submit %>
<% end %>

app/views/offers/index.html.erb
<%= link_to "Home", root_path %><br>
<%= link_to "Create a new offer", new_offer_path %>
<h1>My Offers</h1>


<% @offers.each do |offer| %>
<%= link_to "Edit Offer", edit_offer_path(offer) %>
<%= link_to "Delete", offer_path(offer), method: :delete, data: { confirm: 'Are you sure?' } %>
<p><%= link_to "Title : #{offer.title}", offer_path(offer) %></p>
<p>Ora Coins Asking : <%= offer.token %> Ora Coins</p>
<%= link_to "Coinbase", user_coinbase_omniauth_authorize_path %>
<p>Category : <%= offer.offer_category %></p>
<p>Description : <%= offer.offer_description %></p>
<p>Created at <%= time_ago_in_words(offer.created_at) %> ago</p>
<p>--------------------------------------------------------------</p>

<% end %>

app/views/offers/new.html.erb
<h1>Create New Ora Offer here</h1>
<%= link_to "Home", root_path %>
<p></p>
<%= form_for @offer do |form| %>
	<%= render partial: '/offers/form', object: form %>

  <%= form.submit %>
<% end %>

app/views/offers/show.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Back", offers_path %>
<h1>This is the show page for <%= @offer.user.email %></h1>


<p>Title : <%= @offer.title %></p>
<p>Ora Coins Asking : <%= @offer.token %> Ora Coins</p>
<p>Category : <%= @offer.offer_category %></p>
<p>Description : <%= @offer.offer_description %></p>
<p>Created at <%= time_ago_in_words(@offer.created_at) %> ago</p>