config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#homepage'

  get 'users/show/:id' => 'users#show', as: 'profile_page'

  get 'braintree/new'
  post 'braintree/checkout'

  get 'coinbase/new'
  post 'coinbase/checkout'
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :offers
  resources :requests
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ora</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div><%= link_to "[ Home ]", root_path %></div>
	<% if signed_in? %>
		<div><%= link_to "[ Make a New Offer ]", new_offer_path %><%= link_to "[ Offers Index ]", offers_path %></div> <!-- This is just a test if the link works -->
		<div><%= link_to "[ Make a New Request ]", new_request_path %><%= link_to "[ Requests Index ]", requests_path %></div>  <!-- This is just a test if the link works -->
		<%= button_to "Sign out", destroy_user_session_path, method: :delete %>
	<% else %>
		<div><%= link_to "[ Login ]", new_user_session_path %><%= link_to "[ Sign Up ]", new_user_registration_path %></div>
	<% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/simplemap.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>

  </head>
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 3.1487, lng: 101.644},
          zoom: 8
        });
      }
    </script>  
    <script src="https://maps.googleapis.com/maps/api/js?v=3&callback=initMap"
    async defer></script>
  </body>
</html>